config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'cats#index'

  resources :cats
  resources :cat_rental_requests, only: [:create, :new, :show] do
    member do
      post 'deny'
      post 'approve'
    end
  end

  resources :users, only: [:new, :create]
  resource :users, only: :show

  resource :sessions, only: [:new, :create, :destroy]
end

app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint           not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          default(-1), not null
#
class CatRentalRequest < ApplicationRecord
  include ActionView::Helpers::DateHelper

  belongs_to :cat
  belongs_to :requester,
    class_name: :User,
    foreign_key: :user_id

  validates :start_date, :end_date, presence: true
  validates :status, inclusion: { in: %w[APPROVED PENDING DENIED] }, if: -> { status }
  validate :start_before_end, if: -> { start_date && end_date }
  validate :starts_in_the_future, if: -> { start_date && end_date }
  validate :does_not_overlap_approved_request, if: -> { start_date && end_date }
  validate :cannot_rent_your_own_cat, if: -> { cat_id && user_id }

  def overlapping_requests
    CatRentalRequest.where(cat_id: cat_id)
                    .where.not('? > end_date OR ? < start_date', start_date, end_date)
                    .where.not(id: id)
  end

  def overlapping_approved_requests
    overlapping_requests.where(status: 'APPROVED')
  end

  def overlapping_pending_requests
    overlapping_requests.where(status: 'PENDING')
  end

  def approve!
    return false unless pending?

    transaction do
      overlapping_pending_requests.each(&:deny!)
      update(status: 'APPROVED')
    end
  end

  def deny!
    update(status: 'DENIED')
  end

  def pending?
    status == 'PENDING'
  end

  def cat_name
    cat.name
  end

  def cat_owner
    cat.owner
  end

  def cat_requester
    requester.username
  end

  private

  def start_before_end
    unless start_date < end_date
      errors[:base] << 'Start date must come before end date'
    end
  end

  def does_not_overlap_approved_request
    if overlapping_approved_requests.exists?
      errors[:base] << 'Dates conflict with an existing approved request'
    end
  end

  def cannot_rent_your_own_cat
    if cat.owner == requester
      errors[:user_id] << 'Owner cannot rent their own cat!'
    end
  end

  def starts_in_the_future
    if start_date < Date.today
      errors[:start_date] << 'Start date must be in the future'
    end
  end
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_action :require_current_user
  before_action :user_must_own_cat, only: [:approve, :deny]

  def new
    @cat_rental_request = CatRentalRequest.new
    render :new
  end

  def create
    @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)
    @cat_rental_request.requester = current_user
    if @cat_rental_request.save
      redirect_to cat_rental_request_url(@cat_rental_request)
    else
      flash.now[:errors] = @cat_rental_request.errors.full_messages
      render :new
    end
  end

  def show
    @cat_rental_request = CatRentalRequest.find_by(id: params[:id])
    render :show
  end

  def approve
    # @cat_rental_request = CatRentalRequest.find_by(id: params[:id])
    @cat_rental_request.approve!
    redirect_to cat_url(@cat_rental_request.cat_id)
  end

  def deny
    # @cat_rental_request = CatRentalRequest.find_by(id: params[:id])
    @cat_rental_request.deny!
    redirect_to cat_url(@cat_rental_request.cat_id)
  end

  def user_must_own_cat
    # overrides method in ApplicationController
    @cat_rental_request = CatRentalRequest.find_by(id: params[:id])
    redirect_to cats_url unless @cat_rental_request.cat_owner == current_user
  end

  private

  def cat_rental_request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date)
  end
end

app/views/cat_rental_requests/_cat_rental_request.html.erb
<li>
  Cat: <%= cat_rental_request.cat_name %>;
  Start: <%= cat_rental_request.start_date %>;
  End: <%= cat_rental_request.end_date %>;
  Status: <%= cat_rental_request.status %>;
  Requester: <%= cat_rental_request.cat_requester %>

  <% if cat_rental_request.pending? && cat_rental_request.cat_owner == current_user %>
    <form method='POST'>
    <%= auth_token %>

      <button type='submit'
        formaction='<%= approve_cat_rental_request_path(cat_rental_request) %>'>Approve</button>
      <button type='submit'
        formaction='<%= deny_cat_rental_request_path(cat_rental_request) %>'>Deny</button>
    </form>
  <% end %>
  <br>
  <br>
</li>

app/views/cat_rental_requests/new.html.erb
<h3>New Cat Rental Request</h3>

<%= render 'shared/errors' %>

<form action='<%= cat_rental_requests_path %>' method='POST'>
  <%= auth_token %>

  <label for='cat'>Choose a cat: </label>
  <select id='cat' name='cat_rental_request[cat_id]'>
    <option disabled <%= 'selected' if @cat_rental_request.cat_id.nil? %>>--Select Cat--</option>
    <% Cat.all.each do |katze| %>
      <option value='<%= katze.id %>'
        <%= 'selected' if @cat_rental_request.cat_id == katze.id %>>
        <%= katze.name %>
      </option>
    <% end %>
  </select>

  <br>
  <br>

  <label for='start_date'>Start Date: </label>
  <input id='start_date'
         name='cat_rental_request[start_date]'
         type='date'
         value='<%= @cat_rental_request.start_date %>'>

  <br>
  <br>

  <label for='end_date'>End Date: </label>
  <input id='end_date'
         name='cat_rental_request[end_date]'
         type='date'
         value='<%= @cat_rental_request.end_date %>'>

  <br>
  <br>

  <input type='submit' value='Submit Request'>

</form>

<% content_for :footer do %>
  <p>You're not just renting a cat; you're renting a way of life.</p>
<% end %>

app/views/cat_rental_requests/show.html.erb
<h3>Rental Request</h3>

<h5>Cat: <%= @cat_rental_request.cat_name %></h5>

<ul>
  <li>Start Date: <%= @cat_rental_request.start_date %></li>
  <li>End Date: <%= @cat_rental_request.end_date %></li>
  <li>Status: <%= @cat_rental_request.status %></li>
</ul>