config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'cats#index'

  resources :cats
  resources :cat_rental_requests, only: [:create, :new, :show] do
    member do
      post 'deny'
      post 'approve'
    end
  end

  resources :users, only: [:new, :create]
  resource :users, only: :show

  resource :sessions, only: [:new, :create, :destroy]
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birthdate   :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer          default(-1), not null
#
class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper

  COLORS = %w[black white tuxedo calico orange tortoiseshell]

  validates :birthdate, :color, :name, :sex, :description, presence: true
  validates :color, inclusion: { in: COLORS }, if: -> { color }
  validates :sex, inclusion: %w[M F], if: -> { sex }
  validate :no_future_birthdate, if: -> { birthdate }

  belongs_to :owner,
    class_name: :User,
    foreign_key: :user_id

  has_many :rental_requests,
    class_name: :CatRentalRequest,
    dependent: :destroy

  def age
    time_ago_in_words(birthdate)
  end

  def owner_name
    owner.username
  end

  private

  def no_future_birthdate
    if birthdate > Date.today
      errors[:birthdate] << 'Cat\'s birthdate can\'t be in the future'
    end
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :require_current_user, only: [:new, :edit, :create, :update]
  before_action :user_must_own_cat, only: [:edit, :update, :destroy]

  def index
    @cats = Cat.all
    # fail
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    # @rental_requests = CatRentalRequest.where(cat_id: @cat.id).order(:start_date)
    # moved to view
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.owner = current_user
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def edit
    # @cat is set in :user_must_own_cat callback
    render :edit
  end

  def update
    # @cat is set in :user_must_own_cat callback
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  def destroy
    # @cat is set in :user_must_own_cat callback
    @cat.destroy
    redirect_to cats_url
  end

  private

  def cat_params
    params.require(:cat).permit(:birthdate, :color, :name, :sex, :description)
  end

end

app/views/cats/_cat.html.erb
<li>
  <%= link_to cat.name, cat_path(cat) %>
</li>

app/views/cats/_form.html.erb
<% action = edit ? cat_path(cat) : cats_path %>

<form action='<%= action %>' method='POST'>
  <%= auth_token %>

  <% if edit %>
  <input type='hidden' name='_method' value='PATCH'>
  <% end %>

  <label for='name'>Name</label>
    <input id='name' name='cat[name]' type='text' value='<%= cat.name %>'>
  <br>

  <label for='birthdate'>Birthdate</label>
  <input id='birthdate' name='cat[birthdate]' type='date' value='<%= cat.birthdate %>'>
  <br>

  <label for='color'>Color</label>
  <select id='color' name='cat[color]'>
    <option disabled <%= 'selected' if cat.color.nil? %>>--Select--</option>
    <% Cat::COLORS.each do |color| %>
      <option value='<%= color %>'<%= 'selected' if cat.color == color %>><%= color %></option> 
    <% end %>
  </select>
  <br>

  <input id='female' type='radio' name='cat[sex]' value='F' <%= 'checked' if cat.sex == 'F' %>>
  <label for='female'>Female</label>
  <input id='male' type='radio' name='cat[sex]' value='M' <%= 'checked' if cat.sex == 'M' %>>
  <label for='male'>Male</label>
  <br>

  <label for='description'>Description</label>
  <textarea name='cat[description]'><%= cat.description %></textarea>
  <br>

  <input type='submit' value='<%= edit ? 'Update Cat' : 'Enter New Cat'%>'>

</form>

app/views/cats/edit.html.erb
<h3> Update an existing cat </h3>

<%= render 'form', cat: @cat, edit: true %>

<% content_for :footer do %>
  <p>Can anyone really edit a cat?</p>
<% end %>

app/views/cats/index.html.erb
<h2>All the cats</h2>

<ul>
  <%= render @cats %>
</ul>

<form method='GET'>
  <button type='submit'
    formaction='<%= new_cat_rental_request_path %>'>Rent a Cat</button>
  <button type='submit'
    formaction='<%= new_cat_path %>'>Add a Cat</button>
</form>

app/views/cats/new.html.erb
<h3> Enter a new cat </h3>

<%= render 'form', cat: @cat, edit: false %>

<% content_for :footer do %>
  <p>Use this form to add a cat.</p>
<% end %>

app/views/cats/show.html.erb
<table>
    <thead>
        <tr>
            <th colspan="2"><%= @cat.name %></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Age</td>
            <td><%= @cat.age %></td>
        </tr>
        <tr>
            <td>Color</td>
            <td><%= @cat.color %></td>
        </tr>
        <tr>
            <td>Sex</td>
            <td><%= @cat.sex %></td>
        </tr>
        <tr>
            <td>Description</td>
            <td><%= @cat.description %></td>
        </tr>
        <tr>
            <td>Owner</td>
            <td><%= @cat.owner_name %></td>
        </tr>
    </tbody>
</table>

<% if @cat.owner == current_user %>
    <br>
    <form method='GET' action='<%= edit_cat_path(@cat) %>' style='display:inline;'>
        <button type='submit'>Edit Cat</button>
    </form>
    <form method='POST' action='<%= cat_path(@cat) %>' style='display:inline;'>
        <%= auth_token %>
        <input type='hidden' name='_method' value='<%= 'DELETE' %>'>
        <button type='submit'>Delete Cat</button>
    </form>

<% end %>

<br>
<h5>Rental Requests:</h5>
<ul>
  <%= render @cat.rental_requests.order(:start_date).includes(:requester) %>
</ul>

<% content_for :footer do %>
  <p>Cat Cat Cat Cat Cat</p>
<% end %>