config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'cats#index'

  resources :cats
  resources :cat_rental_requests, only: [:create, :new, :show] do
    member do
      post 'deny'
      post 'approve'
    end
  end

  resources :users, only: [:new, :create]
  resource :users, only: :show

  resource :sessions, only: [:new, :create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>

    <div>
        <form method='GET' action='<%= cats_path %>' style='display: inline;'>
          <button type='submit'>Home</button>
        </form>

    <% if current_user %>
      
        <form method='GET' action='<%= users_path %>' style='display: inline;'>
          <button type='submit'><%= current_user.username %></button>
        </form>
        <form method='POST' action='<%= sessions_path %>' style='display: inline;'>
          <%= auth_token %>
          <input type='hidden' name='_method' value='<%= 'DELETE' %>'>
          <button type='submit'>Logout</button>
        </form>
    <% else %>
      <form method='GET' style='display: inline;'>
        <button type='submit'
          formaction='<%= new_sessions_path %>'>Login</button>
        <button type='submit'
          formaction='<%= new_user_path %>'>Create new account</button>
      </form>
    <% end %>
    </div>
  </header>

  <body>
    <%= yield %>
  </body>

  <footer style='bottom: 0;position: absolute;'>
    <%= yield :footer %>
    Discover the joy of renting a cat!
  </footer>
</html>